package com.e_commerce.shambhu.shipment.entity;

import com.e_commerce.shambhu.common.entity.Auditable;
import com.e_commerce.shambhu.order.entity.Order;
import com.e_commerce.shambhu.shipment.enums.DeliveryPartner;
import com.e_commerce.shambhu.shipment.enums.ShipmentStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(
        name = "shipments",
        indexes = {
                @Index(name = "idx_shipment_order", columnList = "order_id"),
                @Index(name = "idx_tracking_number", columnList = "tracking_number"),
                @Index(name = "idx_shipment_status", columnList = "shipment_status"),
                @Index(name = "idx_delivery_partner", columnList = "delivery_partner")
        },
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tracking_number",
                        columnNames = "tracking_number"
                ),
                @UniqueConstraint(
                        name = "uk_order_shipment",
                        columnNames = "order_id"
                )
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Shipment extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * One shipment per order.
     * Can be changed to OneToMany in future for split shipments.
     */
    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "order_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_shipment_order")
    )
    private Order order;

    /**
     * Internal tracking number generated by our system.
     */
    @Column(
            name = "tracking_number",
            nullable = false,
            unique = true,
            length = 100
    )
    private String trackingNumber;

    /**
     * Tracking number provided by courier.
     */
    @Column(
            name = "courier_tracking_number",
            length = 100
    )
    private String courierTrackingNumber;

    /**
     * Courier shipment reference/order ID.
     */
    @Column(
            name = "courier_reference_id",
            length = 150
    )
    private String courierReferenceId;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "shipment_status",
            nullable = false,
            length = 30
    )
    private ShipmentStatus shipmentStatus;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "delivery_partner",
            nullable = false,
            length = 30
    )
    @Builder.Default
    private DeliveryPartner deliveryPartner = DeliveryPartner.NOT_ASSIGNED;

    @Column(
            name = "shipping_charge",
            nullable = false,
            precision = 19,
            scale = 2
    )
    @Builder.Default
    private BigDecimal shippingCharge = BigDecimal.ZERO;

    /**
     * Expected delivery date.
     */
    private LocalDate estimatedDeliveryDate;

    /**
     * Actual delivery date.
     */
    private LocalDate actualDeliveryDate;

    /**
     * Shipment dispatched from warehouse.
     */
    private LocalDateTime dispatchedAt;

    /**
     * Shipment delivered to customer.
     */
    private LocalDateTime deliveredAt;

    /**
     * Shipment returned to warehouse.
     */
    private LocalDateTime returnedAt;

    /**
     * Courier response payload.
     */
    @Lob
    @Column(name = "courier_response")
    private String courierResponse;

    /**
     * Failure reason (if shipment fails).
     */
    @Column(length = 500)
    private String failureReason;

    /**
     * Internal remarks.
     */
    @Column(length = 500)
    private String remarks;

}
